artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  URL: https://github.com/ldotmithu/Dataset/raw/refs/heads/main/emails.zip
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transfomation:
  root_dir: artifacts/data_transfomation
  data_path: artifacts/data_ingestion/emails.csv

model_train:
  root_dir: artifacts/model_train
  train_data_path:  artifacts\data_transfomation\train.csv
  test_data_path: artifacts\data_transfomation\test.csv
  model_path: artifacts/model_train/model.joblib
  vector_path: artifacts/model_train/vector.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts\data_transfomation\test.csv
  model_path: artifacts/model_train/model.joblib
  vector_path: artifacts/model_train/vector.joblib
  metrics_path: artifacts/model_evaluation/metrics.json
